# Generated by Django 5.0.6 on 2024-05-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_productos_url_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='url_imagen_producto',
            field=models.TextField(null=True),
        ),
    ]
