# Generated by Django 5.0.6 on 2024-05-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_productos_url_imagen_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='url_imagen_producto',
        ),
        migrations.CreateModel(
            name='Imagen_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen_producto', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.productos')),
            ],
        ),
    ]
