# Generated by Django 5.0.6 on 2024-05-11 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_remove_productos_url_imagen_producto_imagen_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imagen_producto',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Productos.productos'),
        ),
    ]
