# Generated by Django 5.0.6 on 2024-05-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_productos_imagen_alter_imagen_producto_idproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen_producto',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
